### ISSUE TITLE
请求支持 docker 镜像

### ISSUE THREAD

**Issue by jony4** [lcomplete/huntly#2]
方便打镜像吗？

**Comment by Jonnyan404** [comment]
随便打了个自用,直接用,或者等官方镜像也行.
```bash
docker run -d --name=huntly -p 8080:8080 jonnyan404/huntly
```

- 提供 `PORT` 变量自定义端口

启动后,访问 ip:8080 即可

**Comment by ItsNoted** [comment]
Will there be an official docker image or compose with persistent storage volumes?

**Comment by lcomplete** [comment]
> Will there be an official docker image or compose with persistent storage volumes?

Yes, will support asap.

**Comment by ItsNoted** [comment]
> > Will there be an official docker image or compose with persistent storage volumes?
> 
> Yes, will support asap.

Also better mobile support would be a big plus. Right now it's not possible to view on mobile devices.
