### ISSUE TITLE
[BUG][SQLITE_ERROR] SQL error or missing database (no such table: tweet_track)

### ISSUE THREAD

**Issue by fillpit** [lcomplete/huntly#23]
用 docker 部署启动后, 第一次访问创建用户报错
<img width="719" alt="image" src="https://user-images.githubusercontent.com/90119466/225826704-3b605d70-618e-49d0-b011-cc0019491965.png">
查看日志输出如下显示
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/90119466/225826816-947fa696-7bd7-4d24-8c6a-4ada9319041b.png">

**Comment by lcomplete** [comment]
检查下目录的文件写入权限，应该是 sqlite 数据库创建失败了。
