### ISSUE TITLE
求问APP_ARGS这个值要如何配置？

### ISSUE THREAD

**Issue by i-iooi-i** [lcomplete/huntly#27]
![image](https://user-images.githubusercontent.com/1827701/226409408-7acf5fac-85bb-4930-a515-e41e26da335d.png)

在部署的时候，拉取latest，环境变量里面多了一个APP_ARGS，请问这里要如何填写呢？

**Comment by lcomplete** [comment]
不填也可以的。

**Comment by i-iooi-i** [comment]
> 不填也可以的。

感谢大佬，已经安排上了√
