### ISSUE TITLE
请问一下 huntly的数据存储在本地的哪里呀？

### ISSUE THREAD

**Issue by sylph520** [lcomplete/huntly#33]
请问一下 huntly的数据存储在本地的哪里呀？🤣是浏览器插件那边还是服务端呀？（比如如果用jar本地运行的时候）
如果想迁移到不同的浏览器或别的电脑或多设备/浏览器同步，可以备份下数据。

**Comment by lcomplete** [comment]
存储在服务端，也可以把服务端跑在本地。

**Comment by sylph520** [comment]
> 存储在服务端，也可以把服务端跑在本地。

👌那么可以导出数据/同步吗？

**Comment by lcomplete** [comment]
数据默认使用 sqlite 数据库存储，默认保存在运行目录下。
