### ISSUE TITLE
前端包体积优化

### ISSUE THREAD

**Issue by SedationH** [lcomplete/huntly#37]
# 背景
自己整了个小服务器进行部署使用，发现初次加载白屏时间较长
![image](https://user-images.githubusercontent.com/56129212/231212354-1d07a5e8-0ad3-4b9e-b71f-5b5ddcedf81a.png)

# 想法
目测有许多优化方案可以搞上，举一些例子
- 分包
- 懒加载
- CDN
- ...

可以提 PR，想先问问 @lcomplete 你的想法

**Comment by SedationH** [comment]
另外想请教下，构建环境下，Java 和 client 前端是咋结合起来的呢？没看明白

**Comment by lcomplete** [comment]
> 另外想请教下，构建环境下，Java 和 client 前端是咋结合起来的呢？没看明白

用到了 frontend-maven-plugin 插件。

**Comment by lcomplete** [comment]
关于你说的优化方案，我觉得加个缓存是最简便易行的。

**Comment by SedationH** [comment]
> 关于你说的优化方案，我觉得加个缓存是最简便易行的。

缓存的优化效果非常好，是应该优先做的，抱歉没先考虑到

webpack 打包会生成下面这个文件
app/client/build/asset-manifest.json
```
{
  "files": {
    "main.css": "/static/css/main.11e4282d.css",
    "main.js": "/static/js/main.d16a3dec.js",
    "static/js/787.43573c90.chunk.js": "/static/js/787.43573c90.chunk.js",
    "index.html": "/index.html",
    "main.11e4282d.css.map": "/static/css/main.11e4282d.css.map",
    "main.d16a3dec.js.map": "/static/js/main.d16a3dec.js.map",
    "787.43573c90.chunk.js.map": "/static/js/787.43573c90.chunk.js.map"
  },
  "entrypoints": [
    "static/css/main.11e4282d.css",
    "static/js/main.d16a3dec.js"
  ]
}
```

hash 在文件内容不变的情况下，hash也不会发生改变。

觉得可以在 ReactAppController 加一处读取这个文件，利用 ETag 来处理缓存的逻辑

**Comment by lcomplete** [comment]
增加静态资源的 cache control 配置应该就可以了，参考：https://www.baeldung.com/cachable-static-assets-with-spring-mvc
