### ISSUE TITLE
为什么我的huntly加载到的twitter信息都不显示图片？

### ISSUE THREAD

**Issue by godpowerscn** [lcomplete/huntly#44]
已经开启了http代理，并在huntly设置了代理地址和端口并启用。即便使用全局（huntly内部不设置代理）也是同样的情况

**Comment by lcomplete** [comment]
huntly 中的代理是用来获取rss的，推特的图片没保存下来，走的是浏览器的代理。

**Comment by godpowerscn** [comment]
我的浏览器是用插件走代理的，这个会产生什么影响吗？这里的浏览器是指我当前在用的浏览器，还是ie?

**Comment by lcomplete** [comment]
当前在用的，就跟你直接访问推特走的代理是一样的。

zelot cart ***@***.***>于2023年5月16日 周二12:03写道：

**Comment by godpowerscn** [comment]
浏览器没问题，但是我在huntly里就是看不到图片（只限于twitter或类似网站），实在让人困惑。还有其他可能吗？

**Comment by lcomplete** [comment]
你从新窗口打开图片，看看图片是不是没走代理。

zelot cart ***@***.***>于2023年5月16日 周二12:22写道：

**Comment by lcomplete** [comment]
你用的啥代理，我用 proxy switch omega 没这个问题。

zelot cart ***@***.***>于2023年5月17日 周三21:23写道：
