### ISSUE TITLE
登出后，再登录返回系统异常

### ISSUE THREAD

**Issue by swxs** [lcomplete/huntly#46]
{"error":{"code":5000,"message":"系统异常","type":"BadCredentialsException"}}

无法连入系统，需要如何解决？

**Comment by lcomplete** [comment]
这好像是账号密码错了呀，如果忘记了就在数据库里把用户删了，再打开页面的时候会提示重建，其他数据不受影响。

swxs ***@***.***>于2023年5月23日 周二18:18写道：
