### ISSUE TITLE
能否不通过拓展方式，直接在网页添加

### ISSUE THREAD

**Issue by bestruirui** [lcomplete/huntly#48]

**Comment by lcomplete** [comment]
目前不支持。

**Comment by bestruirui** [comment]
未来可以考虑加入这个功能吗

**Comment by lcomplete** [comment]
不考虑，插件上其实有开关是否要自动保存网页呀，你可以关闭自动保存，使用手动保存就好了。

另外代码里面通过 url 解析网页文章的实现也都有，要增加这个功能也很容易，如果需要的话可以修改源代码。
