### ISSUE TITLE
请教docker架构下是否可以通过nginx实现https访问?

### ISSUE THREAD

**Issue by cutemanworking** [lcomplete/huntly#54]
我在nginx的配置如下，可以访问，但显示空白:
location /huntly {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://localhost:15080;
            proxy_read_timeout 90;
            proxy_redirect http://localhost:15080;
        }

**Comment by lcomplete** [comment]
不能设置成子目录，换个二级域名或端口吧。

cutemanworking ***@***.***>于2023年12月27日 周三16:40写道：

**Comment by cutemanworking** [comment]
嗯嗯， 换成端口方式就可以了， 感谢!!!!!!
