### ISSUE TITLE
基于 github action 自动构建docker镜像

### ISSUE THREAD

**Issue by eryajf** [lcomplete/huntly#6]
项目非常棒，有一些工作可以基于github action自动化掉，比如docker镜像可以交给action自动构建。

请问是否需要，如果需要，我可以提交一个PR完善这块儿内容。

**Comment by lcomplete** [comment]
这个涉及到开发流程，需要建立 dev 分支，最后合入 main 的再走自动化流程。

欢迎贡献代码。

**Comment by eryajf** [comment]
嗯，action这块儿的增加不会涉及到代码的改动，我将以fork到个人仓库，然后更改之后，提交pr的形式来参与协作。
