### ISSUE TITLE
Twitter无法加载页面。

### ISSUE THREAD

**Issue by dhammavipassi** [lcomplete/huntly#61]
安装了Huntly插件以后，推特无法加载页面。
<img width="1361" alt="Screenshot 2024-04-09 at 6 19 39 PM" src="https://github.com/lcomplete/huntly/assets/127640726/25474a8f-40e2-4ae3-b76f-355d69ea7ae2">

**Comment by lcomplete** [comment]
是不是安装了 uBlock，目前跟这个插件会有冲突导致推特无法加载。

**Comment by dhammavipassi** [comment]
是安装了 uBlock。谢谢！

**Comment by xhy279** [comment]
原因是啥？ 有什么解决办法吗？

**Comment by lcomplete** [comment]
可以先在 huntly 插件的设置中把 auto save tweet 禁用掉。
