### ISSUE TITLE
Caused by: java.sql.SQLException: opening db: 'db.sqlite': Read-only file system

### ISSUE THREAD

**Issue by garywu520** [lcomplete/huntly#8]
On my M1, use java run error

<br>
<br>

```
$ java -Xms128m -Xmx1024m -jar xxx/huntly/huntly-server-0.1.0-SNAPSHOT.jar --server.port=8081
......
Caused by: java.sql.SQLException: opening db: 'db.sqlite': Read-only file system
......
```

**Comment by lcomplete** [comment]
The prompt is a file write permission problem. Find a directory with write permission, put the jar package in it, and try running it again.

**Comment by garywu520** [comment]
same error
Can I specify a db file to store the path through parameters?

**Comment by lcomplete** [comment]
yes, add --huntly.dataDir param, make sure the directory created.
