### ISSUE TITLE
小白请教一下，在dockerhub上搜不到

### ISSUE THREAD

**Issue by nscmiaoxin** [lcomplete/huntly#9]
大神好，感谢您开发的优秀项目，想在nas上部署，现在在dockerhub上还搜不到lcomplete/huntly镜像，怎们解决啊？感谢！

**Comment by lcomplete** [comment]
https://hub.docker.com/r/lcomplete/huntly/tags

**Comment by lcomplete** [comment]
这里有呢。

**Comment by nscmiaoxin** [comment]
> https://hub.docker.com/r/lcomplete/huntly/tags

感谢感谢！！
